version: 0.2

phases:
  pre_build:
    commands:
      - export TZ="Asia/Tokyo"
      - yarn install
      - npm install showdown -g
  build:
    commands:
      - yarn textlint docs/resume.md
      - showdown makehtml -i docs/resume.md -o index.html
  post_build:
    commands:
      - tar cf /tmp/node_modules.tar node_modules
artifacts:
  files:
    - '**/*'
  base-directory: build
cache:
  paths:
    - /tmp/node_modules.tar